version: '3'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    image: ecommercespringboot
    container_name: ecommercespringboot_web
    ports:
      - "8089:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    environment:
      - TZ=UTC+7
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db_mysql
    networks:
      - ecommercespringboot_network

  db_mysql:
    image: mysql:8.0.31
    container_name: ecommercespringboot_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_dev_ecommerce_springboot
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    expose:
      - "3306"
    volumes:
      - /var/lib/mysql
      - /etc/mysql/conf.d 
    networks:
      - ecommercespringboot_network

networks:
  ecommercespringboot_network:
